//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RESTORANDBEntities2 : DbContext
    {
        public RESTORANDBEntities2()
            : base("name=RESTORANDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblBORDROLAR> TblBORDROLAR { get; set; }
        public virtual DbSet<TblCEKSENET> TblCEKSENET { get; set; }
        public virtual DbSet<TblFIRMA> TblFIRMA { get; set; }
        public virtual DbSet<TblGELIR> TblGELIR { get; set; }
        public virtual DbSet<TblGIDER> TblGIDER { get; set; }
        public virtual DbSet<TblGUNLUKHARCAMA> TblGUNLUKHARCAMA { get; set; }
        public virtual DbSet<TblKATEGORI> TblKATEGORI { get; set; }
        public virtual DbSet<TblMAAS> TblMAAS { get; set; }
        public virtual DbSet<TblMASA> TblMASA { get; set; }
        public virtual DbSet<TblMUSTERILER> TblMUSTERILER { get; set; }
        public virtual DbSet<TblPERSONELLER> TblPERSONELLER { get; set; }
        public virtual DbSet<TblREZARVASYON> TblREZARVASYON { get; set; }
        public virtual DbSet<TblSATIS> TblSATIS { get; set; }
        public virtual DbSet<TblSIPARIS> TblSIPARIS { get; set; }
        public virtual DbSet<TblSIPARISDETAY> TblSIPARISDETAY { get; set; }
        public virtual DbSet<TblSTOKHAREKET> TblSTOKHAREKET { get; set; }
        public virtual DbSet<TblURUN> TblURUN { get; set; }
        public virtual DbSet<TblPERSONELODEME> TblPERSONELODEME { get; set; }
        public virtual DbSet<TblMODEME> TblMODEME { get; set; }
    }
}
