//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBORDROLAR
    {
        public int BordroID { get; set; }
        public int PersonelID { get; set; }
        public short Ay { get; set; }
        public short Yil { get; set; }
        public decimal AnaMaas { get; set; }
        public Nullable<decimal> Prim { get; set; }
        public Nullable<decimal> Kesinti { get; set; }
        public Nullable<decimal> Avans { get; set; }
        public Nullable<decimal> ToplamOdeme { get; set; }
        public Nullable<System.DateTime> OdemeTarihi { get; set; }
        public string Aciklama { get; set; }
    
        public virtual TblPERSONELLER TblPERSONELLER { get; set; }
    }
}
