//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFIRMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblFIRMA()
        {
            this.TblGIDER = new HashSet<TblGIDER>();
            this.TblGUNLUKHARCAMA = new HashSet<TblGUNLUKHARCAMA>();
            this.TblSTOKHAREKET = new HashSet<TblSTOKHAREKET>();
            this.TblURUN = new HashSet<TblURUN>();
            this.TblCEKSENET = new HashSet<TblCEKSENET>();
            this.TblMODEME = new HashSet<TblMODEME>();
        }
    
        public int FirmaId { get; set; }
        public string FirmaAdi { get; set; }
        public string Unvan { get; set; }
        public string Telefon { get; set; }
        public string Telefonİki { get; set; }
        public string Email { get; set; }
        public string Adres { get; set; }
        public string WebSitesi { get; set; }
        public string VergiDairesi { get; set; }
        public string HesapNo { get; set; }
        public Nullable<bool> Durumu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblGIDER> TblGIDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblGUNLUKHARCAMA> TblGUNLUKHARCAMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSTOKHAREKET> TblSTOKHAREKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblURUN> TblURUN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCEKSENET> TblCEKSENET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMODEME> TblMODEME { get; set; }
    }
}
