//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGELIR
    {
        public int GelirId { get; set; }
        public string GelirTuru { get; set; }
        public decimal Tutar { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Aciklama { get; set; }
        public int PersonelId { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public string ReferansTablo { get; set; }
        public Nullable<int> ReferansId { get; set; }
    
        public virtual TblMUSTERILER TblMUSTERILER { get; set; }
        public virtual TblPERSONELLER TblPERSONELLER { get; set; }
    }
}
