//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMAAS
    {
        public int MaasTanimID { get; set; }
        public int PersonelID { get; set; }
        public decimal NetTutar { get; set; }
        public System.DateTime BaslangicTarihi { get; set; }
    
        public virtual TblPERSONELLER TblPERSONELLER { get; set; }
    }
}
