//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPERSONELODEME
    {
        public int ID { get; set; }
        public Nullable<int> PERSONEL { get; set; }
        public string TUR { get; set; }
        public Nullable<decimal> ODEMEMIKTARI { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string ACIKLAMA { get; set; }
    
        public virtual TblPERSONELLER TblPERSONELLER { get; set; }
    }
}
