//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblREZARVASYON
    {
        public int RezarvasyonId { get; set; }
        public int MusteriId { get; set; }
        public int MasaNoId { get; set; }
        public int KisiSayisi { get; set; }
        public System.DateTime Tarih { get; set; }
        public System.TimeSpan Saat { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual TblMASA TblMASA { get; set; }
        public virtual TblMUSTERILER TblMUSTERILER { get; set; }
    }
}
