//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblADISYON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblADISYON()
        {
            this.TblADISYON_DETAY = new HashSet<TblADISYON_DETAY>();
            this.TblADISYON_ODEME = new HashSet<TblADISYON_ODEME>();
        }
    
        public int AdisyonId { get; set; }
        public Nullable<int> MasaId { get; set; }
        public Nullable<System.DateTime> AcilisZamani { get; set; }
        public Nullable<System.DateTime> KapanisZamani { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual TblMASA TblMASA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblADISYON_DETAY> TblADISYON_DETAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblADISYON_ODEME> TblADISYON_ODEME { get; set; }
    }
}
