//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCEKSENET
    {
        public int CeksenetId { get; set; }
        public Nullable<int> SatisNo { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public Nullable<int> FirmaId { get; set; }
        public decimal Tutar { get; set; }
        public string OdemeTuru { get; set; }
        public Nullable<int> PersonelId { get; set; }
        public System.DateTime YTarih { get; set; }
        public Nullable<System.DateTime> OTarih { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual TblFIRMA TblFIRMA { get; set; }
        public virtual TblMUSTERILER TblMUSTERILER { get; set; }
        public virtual TblPERSONELLER TblPERSONELLER { get; set; }
        public virtual TblSIPARIS TblSIPARIS { get; set; }
    }
}
