//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFIRMAHAREKET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblFIRMAHAREKET()
        {
            this.TblGIDER = new HashSet<TblGIDER>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UrunId { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> FirmaId { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual TblFIRMA TblFIRMA { get; set; }
        public virtual TblURUN TblURUN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblGIDER> TblGIDER { get; set; }
    }
}
