//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGUNLUKHARCAMA
    {
        public int GunlukId { get; set; }
        public string HarcananYer { get; set; }
        public System.DateTime Tarih { get; set; }
        public System.TimeSpan Saat { get; set; }
        public string Aciklama { get; set; }
        public decimal Tutar { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<int> FirmaId { get; set; }
    
        public virtual TblFIRMA TblFIRMA { get; set; }
        public virtual TblPERSONELLER TblPERSONELLER { get; set; }
    }
}
