//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGIDER
    {
        public int GiderId { get; set; }
        public string GiderTuru { get; set; }
        public decimal Tutar { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Aciklama { get; set; }
        public int PersonelId { get; set; }
        public Nullable<int> FirmaId { get; set; }
        public string ReferansTablo { get; set; }
        public Nullable<int> ReferansId { get; set; }
    
        public virtual TblFIRMA TblFIRMA { get; set; }
        public virtual TblPERSONELLER TblPERSONELLER { get; set; }
    }
}
