//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKULLANICI
    {
        public int KullaniciId { get; set; }
        public string KullaniciAdSoyad { get; set; }
        public string KullaniciEmail { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public string KullaniciResim { get; set; }
        public string Yetki { get; set; }
        public Nullable<bool> GUNLUKHARCAMA { get; set; }
        public Nullable<bool> MUHASEBE { get; set; }
        public Nullable<bool> CEKSENET { get; set; }
        public Nullable<bool> SATISDURUMU { get; set; }
        public Nullable<bool> PERSONEL { get; set; }
        public Nullable<bool> MUSTERIFIRMA { get; set; }
        public Nullable<bool> STOK { get; set; }
        public Nullable<bool> URUNLER { get; set; }
        public Nullable<bool> REZERVASYON { get; set; }
        public Nullable<bool> VERITABANI { get; set; }
        public Nullable<bool> YETKILENDIRMEYAP { get; set; }
    }
}
