//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPAKET
    {
        public int PaketId { get; set; }
        public Nullable<int> PaketNo { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public string Statu { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
