//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSTOKHAREKET
    {
        public int StokHareketId { get; set; }
        public int UrunId { get; set; }
        public Nullable<int> FirmaId { get; set; }
        public string HareketTipi { get; set; }
        public Nullable<decimal> Miktar { get; set; }
        public string BirimTuru { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<System.TimeSpan> Saat { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> PersonelId { get; set; }
    
        public virtual TblFIRMA TblFIRMA { get; set; }
        public virtual TblPERSONELLER TblPERSONELLER { get; set; }
        public virtual TblURUN TblURUN { get; set; }
    }
}
