//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSIPARIS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSIPARIS()
        {
            this.TblCEKSENET = new HashSet<TblCEKSENET>();
            this.TblSIPARISDETAY = new HashSet<TblSIPARISDETAY>();
        }
    
        public int SiparisId { get; set; }
        public int MasaId { get; set; }
        public int PersonelId { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
        public Nullable<bool> OdemeDurumu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCEKSENET> TblCEKSENET { get; set; }
        public virtual TblMASA TblMASA { get; set; }
        public virtual TblPERSONELLER TblPERSONELLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSIPARISDETAY> TblSIPARISDETAY { get; set; }
    }
}
