//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblURUN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblURUN()
        {
            this.TblSIPARISDETAY = new HashSet<TblSIPARISDETAY>();
            this.TblSTOKHAREKET = new HashSet<TblSTOKHAREKET>();
        }
    
        public int UrunId { get; set; }
        public string UrunAdi { get; set; }
        public decimal Fiyat { get; set; }
        public int KategoriId { get; set; }
        public int FirmaId { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> StokMiktari { get; set; }
        public string Birim { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string ResimYolu { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
    
        public virtual TblFIRMA TblFIRMA { get; set; }
        public virtual TblKATEGORI TblKATEGORI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSIPARISDETAY> TblSIPARISDETAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSTOKHAREKET> TblSTOKHAREKET { get; set; }
    }
}
