USE [RESTORANDB]
GO
/****** Object:  Table [dbo].[TblADISYON]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblADISYON](
	[AdisyonId] [int] IDENTITY(1,1) NOT NULL,
	[MasaId] [int] NULL,
	[AcilisZamani] [datetime] NULL,
	[KapanisZamani] [datetime] NULL,
	[Durum] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[AdisyonId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblADISYON_DETAY]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblADISYON_DETAY](
	[DetayId] [int] IDENTITY(1,1) NOT NULL,
	[AdisyonId] [int] NULL,
	[UrunId] [int] NULL,
	[Adet] [int] NULL,
	[Fiyat] [decimal](18, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[DetayId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblADISYON_ODEME]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblADISYON_ODEME](
	[OdemeId] [int] IDENTITY(1,1) NOT NULL,
	[AdisyonId] [int] NOT NULL,
	[OdemeTuru] [nvarchar](50) NULL,
	[OdenenTutar] [decimal](18, 2) NOT NULL,
	[Tarih] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[OdemeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblBORDROLAR]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblBORDROLAR](
	[BordroID] [int] IDENTITY(1,1) NOT NULL,
	[PersonelID] [int] NOT NULL,
	[Ay] [smallint] NOT NULL,
	[Yil] [smallint] NOT NULL,
	[AnaMaas] [decimal](10, 2) NOT NULL,
	[Prim] [decimal](8, 2) NULL,
	[Kesinti] [decimal](8, 2) NULL,
	[Avans] [decimal](8, 2) NULL,
	[ToplamOdeme]  AS (CONVERT([decimal](10,2),(([AnaMaas]+[Prim])-[Kesinti])-[Avans])) PERSISTED,
	[OdemeTarihi] [date] NULL,
	[Aciklama] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[BordroID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblCEKSENET]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblCEKSENET](
	[CeksenetId] [int] IDENTITY(1,1) NOT NULL,
	[SatisNo] [int] NULL,
	[MusteriId] [int] NULL,
	[FirmaId] [int] NULL,
	[Tutar] [decimal](10, 2) NOT NULL,
	[OdemeTuru] [nvarchar](50) NULL,
	[PersonelId] [int] NULL,
	[YTarih] [date] NOT NULL,
	[OTarih] [date] NULL,
	[Aciklama] [nvarchar](200) NULL,
	[Durum] [bit] NULL,
 CONSTRAINT [PK__TblCEKSE__0A4B240B7AEDC236] PRIMARY KEY CLUSTERED 
(
	[CeksenetId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblFIRMA]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblFIRMA](
	[FirmaId] [int] IDENTITY(1,1) NOT NULL,
	[FirmaAdi] [nvarchar](100) NOT NULL,
	[Unvan] [nvarchar](50) NULL,
	[Telefon] [nvarchar](30) NOT NULL,
	[Telefonİki] [nvarchar](30) NULL,
	[Email] [nvarchar](100) NOT NULL,
	[Adres] [nvarchar](200) NOT NULL,
	[WebSitesi] [nvarchar](250) NULL,
	[VergiDairesi] [nvarchar](max) NULL,
	[HesapNo] [nvarchar](max) NULL,
	[Durumu] [bit] NULL,
 CONSTRAINT [PK__TblFIRMA__CD9C5E2FE0AAFC90] PRIMARY KEY CLUSTERED 
(
	[FirmaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblFIRMAHAREKET]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblFIRMAHAREKET](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UrunId] [int] NULL,
	[Aciklama] [nvarchar](100) NULL,
	[FirmaId] [int] NULL,
	[Tutar] [decimal](18, 2) NULL,
	[Adet] [int] NULL,
	[Tarih] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblFIRMAODEME]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblFIRMAODEME](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirmaId] [int] NULL,
	[Aciklama] [nvarchar](100) NULL,
	[Tutar] [decimal](18, 2) NULL,
	[Tarih] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblGELIR]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblGELIR](
	[GelirId] [int] IDENTITY(1,1) NOT NULL,
	[GelirTuru] [nvarchar](100) NOT NULL,
	[Tutar] [decimal](12, 2) NOT NULL,
	[Tarih] [datetime] NULL,
	[Aciklama] [nvarchar](500) NULL,
	[PersonelId] [int] NOT NULL,
	[MusteriId] [int] NULL,
	[ReferansTablo] [nvarchar](50) NULL,
	[ReferansId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[GelirId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblGIDER]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblGIDER](
	[GiderId] [int] IDENTITY(1,1) NOT NULL,
	[GiderTuru] [nvarchar](100) NOT NULL,
	[Tutar] [decimal](12, 2) NOT NULL,
	[Tarih] [datetime] NULL,
	[Aciklama] [nvarchar](500) NULL,
	[PersonelId] [int] NULL,
	[FirmaId] [int] NULL,
	[ReferansTablo] [nvarchar](50) NULL,
	[ReferansId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[GiderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblGUNLUKHARCAMA]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblGUNLUKHARCAMA](
	[GunlukId] [int] IDENTITY(1,1) NOT NULL,
	[HarcananYer] [nvarchar](50) NOT NULL,
	[Tarih] [date] NOT NULL,
	[Saat] [time](7) NOT NULL,
	[Aciklama] [nvarchar](50) NOT NULL,
	[Tutar] [decimal](10, 2) NOT NULL,
	[PersonelID] [int] NULL,
	[FirmaId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[GunlukId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblKATEGORI]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblKATEGORI](
	[KategoriId] [int] IDENTITY(1,1) NOT NULL,
	[KategoriAdi] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[KategoriId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBLKULLANICI]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLKULLANICI](
	[KullaniciId] [int] IDENTITY(1,1) NOT NULL,
	[KullaniciAdSoyad] [nvarchar](100) NULL,
	[KullaniciEmail] [nvarchar](150) NULL,
	[KullaniciAdi] [nvarchar](18) NULL,
	[Sifre] [nvarchar](18) NULL,
	[KullaniciResim] [nvarchar](max) NULL,
	[Yetki] [nvarchar](1) NULL,
	[GUNLUKHARCAMA] [bit] NULL,
	[MUHASEBE] [bit] NULL,
	[CEKSENET] [bit] NULL,
	[SATISDURUMU] [bit] NULL,
	[PERSONEL] [bit] NULL,
	[MUSTERIFIRMA] [bit] NULL,
	[STOK] [bit] NULL,
	[URUNLER] [bit] NULL,
	[REZERVASYON] [bit] NULL,
	[VERITABANI] [bit] NULL,
	[YETKILENDIRMEYAP] [bit] NULL,
 CONSTRAINT [PK_TBLKULLANICI] PRIMARY KEY CLUSTERED 
(
	[KullaniciId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblMAAS]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblMAAS](
	[MaasTanimID] [int] IDENTITY(1,1) NOT NULL,
	[PersonelID] [int] NOT NULL,
	[NetTutar] [decimal](10, 2) NOT NULL,
	[BaslangicTarihi] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaasTanimID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblMASA]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblMASA](
	[MasaId] [int] IDENTITY(1,1) NOT NULL,
	[MasaNo] [int] NOT NULL,
	[Aciklama] [nvarchar](250) NOT NULL,
	[Tutar] [decimal](10, 2) NULL,
	[Statu] [char](1) NULL,
	[Durum] [bit] NOT NULL,
	[RezervasyonSaati] [nvarchar](50) NULL,
 CONSTRAINT [PK__TblMASA__9F94EBF3158AB893] PRIMARY KEY CLUSTERED 
(
	[MasaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblMODEME]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblMODEME](
	[OdemeId] [int] IDENTITY(1,1) NOT NULL,
	[FmusteriID] [int] NULL,
	[BorcTutar] [decimal](18, 0) NULL,
	[OdenenTutar] [decimal](18, 0) NULL,
	[Tarih] [date] NULL,
	[Aciklama] [nvarchar](50) NULL,
	[durum] [bit] NULL,
 CONSTRAINT [PK_TblMODEME] PRIMARY KEY CLUSTERED 
(
	[OdemeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblMUSTERILER]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblMUSTERILER](
	[MusteriId] [int] IDENTITY(1,1) NOT NULL,
	[Ad] [nvarchar](250) NOT NULL,
	[Soyad] [nvarchar](250) NOT NULL,
	[MasaId] [int] NOT NULL,
	[Tarih] [date] NOT NULL,
	[Saat] [time](7) NOT NULL,
	[Aciklama] [nvarchar](250) NOT NULL,
	[Telefon] [nvarchar](20) NULL,
	[Durum] [bit] NOT NULL,
 CONSTRAINT [PK__TblMUSTE__72624791AA3C0E1A] PRIMARY KEY CLUSTERED 
(
	[MusteriId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblPAKET]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblPAKET](
	[PaketId] [int] IDENTITY(1,1) NOT NULL,
	[PaketNo] [int] NULL,
	[Tutar] [decimal](18, 2) NULL,
	[Statu] [char](1) NULL,
	[Durum] [bit] NULL,
 CONSTRAINT [PK_TblPAKET] PRIMARY KEY CLUSTERED 
(
	[PaketId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblPERSONELLER]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblPERSONELLER](
	[PersonelID] [int] IDENTITY(1,1) NOT NULL,
	[Ad] [nvarchar](500) NOT NULL,
	[Soyad] [nvarchar](500) NOT NULL,
	[TCKimlikNo] [nchar](11) NOT NULL,
	[Telefon] [nchar](12) NOT NULL,
	[Adres] [nvarchar](200) NOT NULL,
	[Email] [nvarchar](250) NOT NULL,
	[Pozisyon] [nvarchar](50) NOT NULL,
	[Tarih] [date] NOT NULL,
	[Durum] [bit] NOT NULL,
	[Resim] [nvarchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[PersonelID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[TCKimlikNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblPERSONELODEME]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblPERSONELODEME](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PERSONEL] [int] NULL,
	[TUR] [nvarchar](50) NULL,
	[ODEMEMIKTARI] [decimal](10, 2) NULL,
	[TARIH] [date] NULL,
	[ACIKLAMA] [nvarchar](50) NULL,
 CONSTRAINT [PK_TblPERSONELODEME] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblREZARVASYON]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblREZARVASYON](
	[RezarvasyonId] [int] IDENTITY(1,1) NOT NULL,
	[MusteriId] [int] NOT NULL,
	[MasaNoId] [int] NOT NULL,
	[KisiSayisi] [int] NOT NULL,
	[Tarih] [date] NOT NULL,
	[Saat] [time](7) NOT NULL,
	[Aciklama] [nvarchar](100) NULL,
	[Durum] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[RezarvasyonId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblSATIS]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblSATIS](
	[SatisId] [int] IDENTITY(1,1) NOT NULL,
	[UrunId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SatisId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblSIPARIS]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblSIPARIS](
	[SiparisId] [int] IDENTITY(1,1) NOT NULL,
	[MasaId] [int] NOT NULL,
	[PersonelId] [int] NOT NULL,
	[Tarih] [datetime] NULL,
	[ToplamTutar] [decimal](10, 2) NULL,
	[OdemeDurumu] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[SiparisId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblSIPARISDETAY]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblSIPARISDETAY](
	[SiparisDetayId] [int] IDENTITY(1,1) NOT NULL,
	[SiparisId] [int] NOT NULL,
	[UrunId] [int] NOT NULL,
	[Miktar] [int] NOT NULL,
	[BirimFiyat] [decimal](10, 2) NOT NULL,
	[ToplamTutar]  AS (CONVERT([decimal](10,2),[Miktar]*[BirimFiyat])),
PRIMARY KEY CLUSTERED 
(
	[SiparisDetayId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblSTOKHAREKET]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblSTOKHAREKET](
	[StokHareketId] [int] IDENTITY(1,1) NOT NULL,
	[UrunId] [int] NOT NULL,
	[FirmaId] [int] NULL,
	[HareketTipi] [nvarchar](20) NULL,
	[Miktar] [decimal](10, 2) NULL,
	[BirimTuru] [nvarchar](50) NULL,
	[BirimFiyat] [decimal](10, 2) NULL,
	[Tarih] [date] NULL,
	[Saat] [time](3) NULL,
	[Aciklama] [nvarchar](250) NULL,
	[PersonelId] [int] NULL,
 CONSTRAINT [PK__TblSTOKH__8F9B28E0E51B040A] PRIMARY KEY CLUSTERED 
(
	[StokHareketId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblURUN]    Script Date: 23.03.2026 01:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblURUN](
	[UrunId] [int] IDENTITY(1,1) NOT NULL,
	[UrunAdi] [nvarchar](100) NOT NULL,
	[Fiyat] [decimal](10, 2) NOT NULL,
	[KategoriId] [int] NOT NULL,
	[FirmaId] [int] NOT NULL,
	[Aciklama] [nvarchar](250) NULL,
	[StokMiktari] [int] NULL,
	[Birim] [nvarchar](20) NULL,
	[Durum] [bit] NULL,
	[ResimYolu] [nvarchar](250) NULL,
	[EklenmeTarihi] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[UrunId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TblADISYON_ODEME] ADD  DEFAULT (getdate()) FOR [Tarih]
GO
ALTER TABLE [dbo].[TblBORDROLAR] ADD  DEFAULT ((0)) FOR [Prim]
GO
ALTER TABLE [dbo].[TblBORDROLAR] ADD  DEFAULT ((0)) FOR [Kesinti]
GO
ALTER TABLE [dbo].[TblBORDROLAR] ADD  DEFAULT ((0)) FOR [Avans]
GO
ALTER TABLE [dbo].[TblFIRMA] ADD  CONSTRAINT [DF__TblFIRMA__Durumu__44FF419A]  DEFAULT ((1)) FOR [Durumu]
GO
ALTER TABLE [dbo].[TblGELIR] ADD  DEFAULT (getdate()) FOR [Tarih]
GO
ALTER TABLE [dbo].[TblGIDER] ADD  DEFAULT (getdate()) FOR [Tarih]
GO
ALTER TABLE [dbo].[TblMASA] ADD  CONSTRAINT [DF__TblMASA__Tutar__412EB0B6]  DEFAULT ((0)) FOR [Tutar]
GO
ALTER TABLE [dbo].[TblMASA] ADD  CONSTRAINT [DF__TblMASA__Durum__4222D4EF]  DEFAULT ((0)) FOR [Durum]
GO
ALTER TABLE [dbo].[TblMUSTERILER] ADD  CONSTRAINT [DF__TblMUSTER__Durum__3E52440B]  DEFAULT ((0)) FOR [Durum]
GO
ALTER TABLE [dbo].[TblPERSONELLER] ADD  DEFAULT ((0)) FOR [Durum]
GO
ALTER TABLE [dbo].[TblREZARVASYON] ADD  DEFAULT ((1)) FOR [Durum]
GO
ALTER TABLE [dbo].[TblSIPARIS] ADD  DEFAULT (getdate()) FOR [Tarih]
GO
ALTER TABLE [dbo].[TblSIPARIS] ADD  DEFAULT ((0)) FOR [ToplamTutar]
GO
ALTER TABLE [dbo].[TblSIPARIS] ADD  DEFAULT ((0)) FOR [OdemeDurumu]
GO
ALTER TABLE [dbo].[TblSTOKHAREKET] ADD  CONSTRAINT [DF__TblSTOKHA__Tarih__5812160E]  DEFAULT (getdate()) FOR [Tarih]
GO
ALTER TABLE [dbo].[TblURUN] ADD  DEFAULT ((0)) FOR [StokMiktari]
GO
ALTER TABLE [dbo].[TblURUN] ADD  DEFAULT ('Adet') FOR [Birim]
GO
ALTER TABLE [dbo].[TblURUN] ADD  DEFAULT ((1)) FOR [Durum]
GO
ALTER TABLE [dbo].[TblURUN] ADD  DEFAULT (getdate()) FOR [EklenmeTarihi]
GO
ALTER TABLE [dbo].[TblADISYON]  WITH CHECK ADD  CONSTRAINT [FK_Adisyon_Masa] FOREIGN KEY([MasaId])
REFERENCES [dbo].[TblMASA] ([MasaId])
GO
ALTER TABLE [dbo].[TblADISYON] CHECK CONSTRAINT [FK_Adisyon_Masa]
GO
ALTER TABLE [dbo].[TblADISYON_DETAY]  WITH CHECK ADD  CONSTRAINT [FK_Detay_Adisyon] FOREIGN KEY([AdisyonId])
REFERENCES [dbo].[TblADISYON] ([AdisyonId])
GO
ALTER TABLE [dbo].[TblADISYON_DETAY] CHECK CONSTRAINT [FK_Detay_Adisyon]
GO
ALTER TABLE [dbo].[TblADISYON_DETAY]  WITH CHECK ADD  CONSTRAINT [FK_Detay_Urun] FOREIGN KEY([UrunId])
REFERENCES [dbo].[TblURUN] ([UrunId])
GO
ALTER TABLE [dbo].[TblADISYON_DETAY] CHECK CONSTRAINT [FK_Detay_Urun]
GO
ALTER TABLE [dbo].[TblADISYON_ODEME]  WITH CHECK ADD  CONSTRAINT [FK_Odeme_Adisyon] FOREIGN KEY([AdisyonId])
REFERENCES [dbo].[TblADISYON] ([AdisyonId])
GO
ALTER TABLE [dbo].[TblADISYON_ODEME] CHECK CONSTRAINT [FK_Odeme_Adisyon]
GO
ALTER TABLE [dbo].[TblBORDROLAR]  WITH CHECK ADD FOREIGN KEY([PersonelID])
REFERENCES [dbo].[TblPERSONELLER] ([PersonelID])
GO
ALTER TABLE [dbo].[TblCEKSENET]  WITH CHECK ADD  CONSTRAINT [FK_CekSenet_Firma] FOREIGN KEY([FirmaId])
REFERENCES [dbo].[TblFIRMA] ([FirmaId])
GO
ALTER TABLE [dbo].[TblCEKSENET] CHECK CONSTRAINT [FK_CekSenet_Firma]
GO
ALTER TABLE [dbo].[TblCEKSENET]  WITH CHECK ADD  CONSTRAINT [FK_CekSenet_Musteri] FOREIGN KEY([MusteriId])
REFERENCES [dbo].[TblMUSTERILER] ([MusteriId])
GO
ALTER TABLE [dbo].[TblCEKSENET] CHECK CONSTRAINT [FK_CekSenet_Musteri]
GO
ALTER TABLE [dbo].[TblCEKSENET]  WITH CHECK ADD  CONSTRAINT [FK_CekSenet_Personel] FOREIGN KEY([PersonelId])
REFERENCES [dbo].[TblPERSONELLER] ([PersonelID])
GO
ALTER TABLE [dbo].[TblCEKSENET] CHECK CONSTRAINT [FK_CekSenet_Personel]
GO
ALTER TABLE [dbo].[TblCEKSENET]  WITH CHECK ADD  CONSTRAINT [FK_CekSenet_Siparis] FOREIGN KEY([SatisNo])
REFERENCES [dbo].[TblSIPARIS] ([SiparisId])
GO
ALTER TABLE [dbo].[TblCEKSENET] CHECK CONSTRAINT [FK_CekSenet_Siparis]
GO
ALTER TABLE [dbo].[TblFIRMAHAREKET]  WITH CHECK ADD  CONSTRAINT [FK_TblFIRMAHAREKET_TblFIRMA] FOREIGN KEY([FirmaId])
REFERENCES [dbo].[TblFIRMA] ([FirmaId])
GO
ALTER TABLE [dbo].[TblFIRMAHAREKET] CHECK CONSTRAINT [FK_TblFIRMAHAREKET_TblFIRMA]
GO
ALTER TABLE [dbo].[TblFIRMAHAREKET]  WITH CHECK ADD  CONSTRAINT [FK_TblFIRMAHAREKET_TblURUN] FOREIGN KEY([UrunId])
REFERENCES [dbo].[TblURUN] ([UrunId])
GO
ALTER TABLE [dbo].[TblFIRMAHAREKET] CHECK CONSTRAINT [FK_TblFIRMAHAREKET_TblURUN]
GO
ALTER TABLE [dbo].[TblFIRMAODEME]  WITH CHECK ADD  CONSTRAINT [FK_TblFIRMAODEME_TblFIRMA] FOREIGN KEY([FirmaId])
REFERENCES [dbo].[TblFIRMA] ([FirmaId])
GO
ALTER TABLE [dbo].[TblFIRMAODEME] CHECK CONSTRAINT [FK_TblFIRMAODEME_TblFIRMA]
GO
ALTER TABLE [dbo].[TblGELIR]  WITH CHECK ADD  CONSTRAINT [FK_Gelir_Musteri] FOREIGN KEY([MusteriId])
REFERENCES [dbo].[TblMUSTERILER] ([MusteriId])
GO
ALTER TABLE [dbo].[TblGELIR] CHECK CONSTRAINT [FK_Gelir_Musteri]
GO
ALTER TABLE [dbo].[TblGELIR]  WITH CHECK ADD  CONSTRAINT [FK_Gelir_Personel] FOREIGN KEY([PersonelId])
REFERENCES [dbo].[TblPERSONELLER] ([PersonelID])
GO
ALTER TABLE [dbo].[TblGELIR] CHECK CONSTRAINT [FK_Gelir_Personel]
GO
ALTER TABLE [dbo].[TblGIDER]  WITH CHECK ADD  CONSTRAINT [FK_Gider_Firma] FOREIGN KEY([FirmaId])
REFERENCES [dbo].[TblFIRMA] ([FirmaId])
GO
ALTER TABLE [dbo].[TblGIDER] CHECK CONSTRAINT [FK_Gider_Firma]
GO
ALTER TABLE [dbo].[TblGIDER]  WITH CHECK ADD  CONSTRAINT [FK_Gider_Personel] FOREIGN KEY([PersonelId])
REFERENCES [dbo].[TblPERSONELLER] ([PersonelID])
GO
ALTER TABLE [dbo].[TblGIDER] CHECK CONSTRAINT [FK_Gider_Personel]
GO
ALTER TABLE [dbo].[TblGUNLUKHARCAMA]  WITH CHECK ADD  CONSTRAINT [FK_GunlukHarcama_Firma] FOREIGN KEY([FirmaId])
REFERENCES [dbo].[TblFIRMA] ([FirmaId])
GO
ALTER TABLE [dbo].[TblGUNLUKHARCAMA] CHECK CONSTRAINT [FK_GunlukHarcama_Firma]
GO
ALTER TABLE [dbo].[TblGUNLUKHARCAMA]  WITH CHECK ADD  CONSTRAINT [FK_GunlukHarcama_Personel] FOREIGN KEY([PersonelID])
REFERENCES [dbo].[TblPERSONELLER] ([PersonelID])
GO
ALTER TABLE [dbo].[TblGUNLUKHARCAMA] CHECK CONSTRAINT [FK_GunlukHarcama_Personel]
GO
ALTER TABLE [dbo].[TblMAAS]  WITH CHECK ADD  CONSTRAINT [FK_TblMaas_Personel] FOREIGN KEY([PersonelID])
REFERENCES [dbo].[TblPERSONELLER] ([PersonelID])
GO
ALTER TABLE [dbo].[TblMAAS] CHECK CONSTRAINT [FK_TblMaas_Personel]
GO
ALTER TABLE [dbo].[TblMODEME]  WITH CHECK ADD  CONSTRAINT [FK_TblMusteriOdeme_TblFIRMA] FOREIGN KEY([FmusteriID])
REFERENCES [dbo].[TblFIRMA] ([FirmaId])
GO
ALTER TABLE [dbo].[TblMODEME] CHECK CONSTRAINT [FK_TblMusteriOdeme_TblFIRMA]
GO
ALTER TABLE [dbo].[TblPERSONELODEME]  WITH CHECK ADD  CONSTRAINT [FK_Personeller_Odeme] FOREIGN KEY([PERSONEL])
REFERENCES [dbo].[TblPERSONELLER] ([PersonelID])
GO
ALTER TABLE [dbo].[TblPERSONELODEME] CHECK CONSTRAINT [FK_Personeller_Odeme]
GO
ALTER TABLE [dbo].[TblREZARVASYON]  WITH CHECK ADD  CONSTRAINT [FK_Rezervasyon_Masa] FOREIGN KEY([MasaNoId])
REFERENCES [dbo].[TblMASA] ([MasaId])
GO
ALTER TABLE [dbo].[TblREZARVASYON] CHECK CONSTRAINT [FK_Rezervasyon_Masa]
GO
ALTER TABLE [dbo].[TblREZARVASYON]  WITH CHECK ADD  CONSTRAINT [FK_TblRezarvasyon_Musteri] FOREIGN KEY([MusteriId])
REFERENCES [dbo].[TblMUSTERILER] ([MusteriId])
GO
ALTER TABLE [dbo].[TblREZARVASYON] CHECK CONSTRAINT [FK_TblRezarvasyon_Musteri]
GO
ALTER TABLE [dbo].[TblSIPARIS]  WITH CHECK ADD  CONSTRAINT [FK_Siparis_Masa] FOREIGN KEY([MasaId])
REFERENCES [dbo].[TblMASA] ([MasaId])
GO
ALTER TABLE [dbo].[TblSIPARIS] CHECK CONSTRAINT [FK_Siparis_Masa]
GO
ALTER TABLE [dbo].[TblSIPARIS]  WITH CHECK ADD  CONSTRAINT [FK_Siparis_Personel] FOREIGN KEY([PersonelId])
REFERENCES [dbo].[TblPERSONELLER] ([PersonelID])
GO
ALTER TABLE [dbo].[TblSIPARIS] CHECK CONSTRAINT [FK_Siparis_Personel]
GO
ALTER TABLE [dbo].[TblSIPARISDETAY]  WITH CHECK ADD  CONSTRAINT [FK_SiparisDetay_Siparis] FOREIGN KEY([SiparisId])
REFERENCES [dbo].[TblSIPARIS] ([SiparisId])
GO
ALTER TABLE [dbo].[TblSIPARISDETAY] CHECK CONSTRAINT [FK_SiparisDetay_Siparis]
GO
ALTER TABLE [dbo].[TblSIPARISDETAY]  WITH CHECK ADD  CONSTRAINT [FK_SiparisDetay_Urun] FOREIGN KEY([UrunId])
REFERENCES [dbo].[TblURUN] ([UrunId])
GO
ALTER TABLE [dbo].[TblSIPARISDETAY] CHECK CONSTRAINT [FK_SiparisDetay_Urun]
GO
ALTER TABLE [dbo].[TblSTOKHAREKET]  WITH CHECK ADD  CONSTRAINT [FK_StokHareket_Firma] FOREIGN KEY([FirmaId])
REFERENCES [dbo].[TblFIRMA] ([FirmaId])
GO
ALTER TABLE [dbo].[TblSTOKHAREKET] CHECK CONSTRAINT [FK_StokHareket_Firma]
GO
ALTER TABLE [dbo].[TblSTOKHAREKET]  WITH CHECK ADD  CONSTRAINT [FK_StokHareket_Personel] FOREIGN KEY([PersonelId])
REFERENCES [dbo].[TblPERSONELLER] ([PersonelID])
GO
ALTER TABLE [dbo].[TblSTOKHAREKET] CHECK CONSTRAINT [FK_StokHareket_Personel]
GO
ALTER TABLE [dbo].[TblSTOKHAREKET]  WITH CHECK ADD  CONSTRAINT [FK_StokHareket_Urun] FOREIGN KEY([UrunId])
REFERENCES [dbo].[TblURUN] ([UrunId])
GO
ALTER TABLE [dbo].[TblSTOKHAREKET] CHECK CONSTRAINT [FK_StokHareket_Urun]
GO
ALTER TABLE [dbo].[TblURUN]  WITH CHECK ADD  CONSTRAINT [FK_TblUrun_Firma] FOREIGN KEY([FirmaId])
REFERENCES [dbo].[TblFIRMA] ([FirmaId])
GO
ALTER TABLE [dbo].[TblURUN] CHECK CONSTRAINT [FK_TblUrun_Firma]
GO
ALTER TABLE [dbo].[TblURUN]  WITH CHECK ADD  CONSTRAINT [FK_UrunKategori] FOREIGN KEY([KategoriId])
REFERENCES [dbo].[TblKATEGORI] ([KategoriId])
GO
ALTER TABLE [dbo].[TblURUN] CHECK CONSTRAINT [FK_UrunKategori]
GO
ALTER TABLE [dbo].[TblPERSONELLER]  WITH CHECK ADD CHECK  (([TCKimlikNo] like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0,2,4,6,8]'))
GO
ALTER TABLE [dbo].[TblREZARVASYON]  WITH CHECK ADD CHECK  (([KisiSayisi]>=(1) AND [KisiSayisi]<=(20)))
GO
ALTER TABLE [dbo].[TblSTOKHAREKET]  WITH CHECK ADD  CONSTRAINT [CK__TblSTOKHA__Harek__571DF1D5] CHECK  (([HareketTipi]='Zayi' OR [HareketTipi]='İade' OR [HareketTipi]='Satış' OR [HareketTipi]='Stok Girişi'))
GO
ALTER TABLE [dbo].[TblSTOKHAREKET] CHECK CONSTRAINT [CK__TblSTOKHA__Harek__571DF1D5]
GO
