USE RESTORANDB
GO

ALTER TABLE TblMAAS
ADD CONSTRAINT FK_TblMaas_Personel
FOREIGN KEY (PersonelId) REFERENCES TblPERSONELLER(PersonelID)
ON DELETE NO ACTION ON UPDATE NO ACTION;


ALTER TABLE TblMUSTERILER
ADD CONSTRAINT FK_TblMusteriler_Masa
FOREIGN KEY (MasaId) REFERENCES TblMASA(MasaId)
ON DELETE NO ACTION ON UPDATE NO ACTION;


ALTER TABLE TblURUN
ADD CONSTRAINT FK_UrunKategori
FOREIGN KEY(KategoriId) REFERENCES TblKATEGORI(KategoriId)
ON DELETE NO ACTION ON UPDATE NO ACTION;


ALTER TABLE TblURUN
ADD CONSTRAINT FK_TblUrun_Firma
FOREIGN KEY (FirmaId) REFERENCES TblFIRMA(FirmaId)
ON DELETE NO ACTION ON UPDATE NO ACTION;


ALTER TABLE TblREZARVASYON
ADD CONSTRAINT FK_TblRezarvasyon_Musteri
FOREIGN KEY (MusteriId) REFERENCES TblMUSTERILER(MusteriId)
ON DELETE NO ACTION ON UPDATE NO ACTION;


ALTER TABLE TblREZARVASYON
ADD CONSTRAINT FK_Rezervasyon_Masa
FOREIGN KEY (MasaNoId) REFERENCES TblMASA(MasaId)
ON DELETE NO ACTION ON UPDATE NO ACTION;


ALTER TABLE TblGUNLUKHARCAMA
ADD CONSTRAINT FK_GunlukHarcama_Personel
FOREIGN KEY (PersonelID) REFERENCES TblPERSONELLER(PersonelID)
ON DELETE NO ACTION ON UPDATE NO ACTION;


ALTER TABLE TblGUNLUKHARCAMA
ADD CONSTRAINT FK_GunlukHarcama_Firma
FOREIGN KEY (FirmaId) REFERENCES TblFIRMA(FirmaId)
ON DELETE NO ACTION ON UPDATE NO ACTION;


ALTER TABLE TblCEKSENET
ADD CONSTRAINT FK_CekSenet_Siparis
FOREIGN KEY (SatisNo) REFERENCES TblSIPARIS(SiparisId)
ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

ALTER TABLE TblCEKSENET
ADD CONSTRAINT FK_CekSenet_Musteri
FOREIGN KEY (MusteriId) REFERENCES TblMUSTERILER(MusteriId)
ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

ALTER TABLE TblCEKSENET
ADD CONSTRAINT FK_CekSenet_Personel
FOREIGN KEY (PersonelId) REFERENCES TblPERSONELLER(PersonelID)
ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

ALTER TABLE TblSIPARIS
ADD CONSTRAINT FK_Siparis_Masa
FOREIGN KEY (MasaId) REFERENCES TblMASA(MasaId)
ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

ALTER TABLE TblSIPARIS
ADD CONSTRAINT FK_Siparis_Personel
FOREIGN KEY (PersonelId) REFERENCES TblPERSONELLER(PersonelID)
ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

ALTER TABLE TblSIPARISDETAY
ADD CONSTRAINT FK_SiparisDetay_Siparis
FOREIGN KEY (SiparisId) REFERENCES TblSIPARIS(SiparisId)
ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

ALTER TABLE TblSIPARISDETAY
ADD CONSTRAINT FK_SiparisDetay_Urun
FOREIGN KEY (UrunId) REFERENCES TblURUN(UrunId)
ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

ALTER TABLE TblSTOKHAREKET
ADD CONSTRAINT FK_StokHareket_Urun
FOREIGN KEY (UrunId) REFERENCES TblURUN(UrunId)
ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

ALTER TABLE TblSTOKHAREKET
ADD CONSTRAINT FK_StokHareket_Firma
FOREIGN KEY (FirmaId) REFERENCES TblFIRMA(FirmaId)
ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

ALTER TABLE TblSTOKHAREKET
ADD CONSTRAINT FK_StokHareket_Personel
FOREIGN KEY (PersonelId) REFERENCES TblPERSONELLER(PersonelID)
ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

ALTER TABLE TblGIDER
ADD CONSTRAINT FK_Gider_Personel
FOREIGN KEY (PersonelId) REFERENCES TblPERSONELLER(PersonelID)
ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

ALTER TABLE TblGIDER
ADD CONSTRAINT FK_Gider_Firma
FOREIGN KEY (FirmaId) REFERENCES TblFIRMA(FirmaId)
ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

ALTER TABLE TblGELIR
ADD CONSTRAINT FK_Gelir_Personel
FOREIGN KEY (PersonelId) REFERENCES TblPERSONELLER(PersonelID)
ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

ALTER TABLE TblGELIR
ADD CONSTRAINT FK_Gelir_Musteri
FOREIGN KEY (MusteriId) REFERENCES TblMUSTERILER(MusteriId)
ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
ALTER TABLE TblCEKSENET
ADD CONSTRAINT FK_CekSenet_Firma
FOREIGN KEY (FirmaId) REFERENCES TblFIRMA(FirmaId)
ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
ALTER TABLE  TblPERSONELODEME
ADD CONSTRAINT FK_Personeller_Odeme
FOREIGN KEY (PERSONEL) REFERENCES TblPERSONELLER( PersonelID)
