//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLADISYONLAR
    {
        public TBLADISYONLAR()
        {
            this.TBLODEME = new HashSet<TBLODEME>();
            this.TBLSIPARISLER = new HashSet<TBLSIPARISLER>();
        }
    
        public int ADISYONID { get; set; }
        public Nullable<int> MASAID { get; set; }
        public Nullable<System.DateTime> ADISYONTARIHI { get; set; }
        public Nullable<decimal> TOPLAMTUTAR { get; set; }
        public Nullable<decimal> INDIRIMTUTARI { get; set; }
        public Nullable<decimal> KDVTUTARI { get; set; }
        public string ODEMEDURUMU { get; set; }
    
        public virtual TBLMASALAR TBLMASALAR { get; set; }
        public virtual ICollection<TBLODEME> TBLODEME { get; set; }
        public virtual ICollection<TBLSIPARISLER> TBLSIPARISLER { get; set; }
    }
}
