//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBORDROLAR
    {
        public int BordroID { get; set; }
        public int PersonelID { get; set; }
        public short Ay { get; set; }
        public short Yil { get; set; }
        public decimal AnaMaas { get; set; }
        public Nullable<decimal> Prim { get; set; }
        public Nullable<decimal> Kesinti { get; set; }
        public Nullable<decimal> Avans { get; set; }
        public Nullable<decimal> ToplamOdeme { get; set; }
        public Nullable<System.DateTime> OdemeTarihi { get; set; }
    
        public virtual TblPERSONELLER TblPERSONELLER { get; set; }
    }
}
