//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCEKSENET
    {
        public int CEKSENETID { get; set; }
        public string TIP { get; set; }
        public Nullable<System.DateTime> ODEMETARIHI { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string ISLEMTURU { get; set; }
        public Nullable<int> ILGILITEDARIKCID { get; set; }
        public Nullable<int> ILGILIGIDERID { get; set; }
        public string DURUM { get; set; }
    
        public virtual TBLGIDER TBLGIDER { get; set; }
        public virtual TBLTEDARIKCILER TBLTEDARIKCILER { get; set; }
    }
}
