//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGELIR
    {
        public int GelirId { get; set; }
        public string GelirTuru { get; set; }
        public decimal Tutar { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Aciklama { get; set; }
        public int PersonelId { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public string ReferansTablo { get; set; }
        public Nullable<int> ReferansId { get; set; }
    
        public virtual TblMUSTERILER TblMUSTERILER { get; set; }
        public virtual TblPERSONELLER TblPERSONELLER { get; set; }
    }
}
