//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGUNLUKHARCAMA
    {
        public int GunlukId { get; set; }
        public string HarcananYer { get; set; }
        public System.DateTime Tarih { get; set; }
        public System.TimeSpan Saat { get; set; }
        public string Aciklama { get; set; }
        public decimal Tutar { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<int> FirmaId { get; set; }
    
        public virtual TblFIRMA TblFIRMA { get; set; }
        public virtual TblPERSONELLER TblPERSONELLER { get; set; }
    }
}
