//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMALZEMELER
    {
        public TBLMALZEMELER()
        {
            this.TBLSTOKTAKIP = new HashSet<TBLSTOKTAKIP>();
            this.TBLTARIFLER = new HashSet<TBLTARIFLER>();
        }
    
        public int MALZEMEID { get; set; }
        public int TEDARIKCID { get; set; }
        public string MALZEMEADI { get; set; }
        public string OLCUMBIRIMI { get; set; }
        public Nullable<decimal> MEVCUTSTOK { get; set; }
    
        public virtual TBLTEDARIKCILER TBLTEDARIKCILER { get; set; }
        public virtual ICollection<TBLSTOKTAKIP> TBLSTOKTAKIP { get; set; }
        public virtual ICollection<TBLTARIFLER> TBLTARIFLER { get; set; }
    }
}
