//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMAAS
    {
        public int MAASID { get; set; }
        public int CALISANID { get; set; }
        public Nullable<decimal> ODEME { get; set; }
        public Nullable<decimal> SAATLIKUCRET { get; set; }
        public Nullable<decimal> CALISILANSAAT { get; set; }
        public Nullable<decimal> FAZLAMESAISAAT { get; set; }
        public Nullable<decimal> BRUTMAAS { get; set; }
        public Nullable<decimal> KESINTILER { get; set; }
        public Nullable<decimal> NETMAAS { get; set; }
        public Nullable<System.DateTime> ODEMETARIHI { get; set; }
        public Nullable<decimal> AVANS { get; set; }
    
        public virtual TBLCALISANLAR TBLCALISANLAR { get; set; }
    }
}
