//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMUSTERILER
    {
        public TBLMUSTERILER()
        {
            this.TBLREZERVASYONLAR = new HashSet<TBLREZERVASYONLAR>();
            this.TBLSIPARISLER = new HashSet<TBLSIPARISLER>();
        }
    
        public int MUSTERID { get; set; }
        public string AD { get; set; }
        public string SOYADI { get; set; }
        public string TELEFON { get; set; }
        public string EMAIL { get; set; }
    
        public virtual ICollection<TBLREZERVASYONLAR> TBLREZERVASYONLAR { get; set; }
        public virtual ICollection<TBLSIPARISLER> TBLSIPARISLER { get; set; }
    }
}
