//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPERSONELHAREKETLERI
    {
        public int HAREKETID { get; set; }
        public Nullable<int> CALISANID { get; set; }
        public string HAREKETTIPI { get; set; }
        public Nullable<System.DateTime> HAREKETZAMANI { get; set; }
        public Nullable<System.DateTime> CALISMATARIHI { get; set; }
    
        public virtual TBLCALISANLAR TBLCALISANLAR { get; set; }
    }
}
