//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLREZERVASYONLAR
    {
        public int REZERVASYONID { get; set; }
        public Nullable<int> MASAID { get; set; }
        public Nullable<int> MUSTERID { get; set; }
        public Nullable<System.DateTime> TARIHSAAT { get; set; }
        public Nullable<int> KISISAYISI { get; set; }
        public string Durum { get; set; }
    
        public virtual TBLMASALAR TBLMASALAR { get; set; }
        public virtual TBLMUSTERILER TBLMUSTERILER { get; set; }
    }
}
