//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSIPARISLER
    {
        public TBLSIPARISLER()
        {
            this.TBLDETAYSIPARIS = new HashSet<TBLDETAYSIPARIS>();
        }
    
        public int SIPARISID { get; set; }
        public Nullable<int> MASAID { get; set; }
        public Nullable<int> CALISANID { get; set; }
        public Nullable<int> MUSTERID { get; set; }
        public Nullable<int> ADISYONID { get; set; }
        public Nullable<System.DateTime> SIPARISTARIHI { get; set; }
        public Nullable<decimal> TOPLAMTUTAR { get; set; }
        public string DURUM { get; set; }
    
        public virtual TBLADISYONLAR TBLADISYONLAR { get; set; }
        public virtual TBLCALISANLAR TBLCALISANLAR { get; set; }
        public virtual ICollection<TBLDETAYSIPARIS> TBLDETAYSIPARIS { get; set; }
        public virtual TBLMASALAR TBLMASALAR { get; set; }
        public virtual TBLMUSTERILER TBLMUSTERILER { get; set; }
    }
}
