//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSIPARIS
    {
        public TblSIPARIS()
        {
            this.TblCEKSENET = new HashSet<TblCEKSENET>();
            this.TblSIPARISDETAY = new HashSet<TblSIPARISDETAY>();
        }
    
        public int SiparisId { get; set; }
        public int MasaId { get; set; }
        public int PersonelId { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
        public Nullable<bool> OdemeDurumu { get; set; }
    
        public virtual ICollection<TblCEKSENET> TblCEKSENET { get; set; }
        public virtual TblMASA TblMASA { get; set; }
        public virtual TblPERSONELLER TblPERSONELLER { get; set; }
        public virtual ICollection<TblSIPARISDETAY> TblSIPARISDETAY { get; set; }
    }
}
