//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTEDARIKCILER
    {
        public TBLTEDARIKCILER()
        {
            this.TBLCEKSENET = new HashSet<TBLCEKSENET>();
            this.TBLGIDER = new HashSet<TBLGIDER>();
            this.TBLMALZEMELER = new HashSet<TBLMALZEMELER>();
            this.TBLSTOKTAKIP = new HashSet<TBLSTOKTAKIP>();
        }
    
        public int ID { get; set; }
        public string AD { get; set; }
        public string TELEFON { get; set; }
        public string ADRES { get; set; }
    
        public virtual ICollection<TBLCEKSENET> TBLCEKSENET { get; set; }
        public virtual ICollection<TBLGIDER> TBLGIDER { get; set; }
        public virtual ICollection<TBLMALZEMELER> TBLMALZEMELER { get; set; }
        public virtual ICollection<TBLSTOKTAKIP> TBLSTOKTAKIP { get; set; }
    }
}
