//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTARIFLER
    {
        public int TARIFID { get; set; }
        public Nullable<int> URUNID { get; set; }
        public Nullable<int> MALZEMEID { get; set; }
        public Nullable<decimal> KULLANILANMIKTAR { get; set; }
        public string ACIKLAMA { get; set; }
    
        public virtual TBLMALZEMELER TBLMALZEMELER { get; set; }
        public virtual TBLURUNLER TBLURUNLER { get; set; }
    }
}
