//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblURUN
    {
        public TblURUN()
        {
            this.TblSIPARISDETAY = new HashSet<TblSIPARISDETAY>();
            this.TblSTOKHAREKET = new HashSet<TblSTOKHAREKET>();
        }
    
        public int UrunId { get; set; }
        public string UrunAdi { get; set; }
        public decimal Fiyat { get; set; }
        public int KategoriId { get; set; }
        public int FirmaId { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> StokMiktari { get; set; }
        public string Birim { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string ResimYolu { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
    
        public virtual TblFIRMA TblFIRMA { get; set; }
        public virtual TblKATEGORI TblKATEGORI { get; set; }
        public virtual ICollection<TblSIPARISDETAY> TblSIPARISDETAY { get; set; }
        public virtual ICollection<TblSTOKHAREKET> TblSTOKHAREKET { get; set; }
    }
}
