//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUNKATAGORI
    {
        public TBLURUNKATAGORI()
        {
            this.TBLURUNLER = new HashSet<TBLURUNLER>();
        }
    
        public int KATAGORID { get; set; }
        public string KATAGORIADI { get; set; }
    
        public virtual ICollection<TBLURUNLER> TBLURUNLER { get; set; }
    }
}
