//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestoranYonetimDBEntities2 : DbContext
    {
        public RestoranYonetimDBEntities2()
            : base("name=RestoranYonetimDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TBLADISYONLAR> TBLADISYONLAR { get; set; }
        public DbSet<TBLCALISANLAR> TBLCALISANLAR { get; set; }
        public DbSet<TBLCALISANVARDIYA> TBLCALISANVARDIYA { get; set; }
        public DbSet<TBLCEKSENET> TBLCEKSENET { get; set; }
        public DbSet<TBLDETAYSIPARIS> TBLDETAYSIPARIS { get; set; }
        public DbSet<TBLGIDER> TBLGIDER { get; set; }
        public DbSet<TBLMAAS> TBLMAAS { get; set; }
        public DbSet<TBLMALZEMELER> TBLMALZEMELER { get; set; }
        public DbSet<TBLMASALAR> TBLMASALAR { get; set; }
        public DbSet<TBLMUSTERILER> TBLMUSTERILER { get; set; }
        public DbSet<TBLODEME> TBLODEME { get; set; }
        public DbSet<TBLPERSONELHAREKETLERI> TBLPERSONELHAREKETLERI { get; set; }
        public DbSet<TBLREZERVASYONLAR> TBLREZERVASYONLAR { get; set; }
        public DbSet<TBLSIPARISLER> TBLSIPARISLER { get; set; }
        public DbSet<TBLSTOKTAKIP> TBLSTOKTAKIP { get; set; }
        public DbSet<TBLTARIFLER> TBLTARIFLER { get; set; }
        public DbSet<TBLTEDARIKCILER> TBLTEDARIKCILER { get; set; }
        public DbSet<TBLURUNKATAGORI> TBLURUNKATAGORI { get; set; }
        public DbSet<TBLURUNLER> TBLURUNLER { get; set; }
        public DbSet<TBLVARDIYALAR> TBLVARDIYALAR { get; set; }
    }
}
