//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCALISANVARDIYA
    {
        public int CALISANVARDIYAID { get; set; }
        public Nullable<int> CALISANID { get; set; }
        public Nullable<int> VARDIYAID { get; set; }
        public Nullable<System.DateTime> CALISMATARIHI { get; set; }
    
        public virtual TBLCALISANLAR TBLCALISANLAR { get; set; }
        public virtual TBLVARDIYALAR TBLVARDIYALAR { get; set; }
    }
}
