//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCALISANLAR
    {
        public TBLCALISANLAR()
        {
            this.TBLCALISANVARDIYA = new HashSet<TBLCALISANVARDIYA>();
            this.TBLMAAS = new HashSet<TBLMAAS>();
            this.TBLPERSONELHAREKETLERI = new HashSet<TBLPERSONELHAREKETLERI>();
            this.TBLSIPARISLER = new HashSet<TBLSIPARISLER>();
        }
    
        public int CALISANID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string POZISYON { get; set; }
        public string TELEFON { get; set; }
        public string ADRES { get; set; }
        public string MAIL { get; set; }
        public Nullable<System.DateTime> ISGIRIS { get; set; }
        public Nullable<bool> DURUMU { get; set; }
        public string Resimler { get; set; }
    
        public virtual ICollection<TBLCALISANVARDIYA> TBLCALISANVARDIYA { get; set; }
        public virtual ICollection<TBLMAAS> TBLMAAS { get; set; }
        public virtual ICollection<TBLPERSONELHAREKETLERI> TBLPERSONELHAREKETLERI { get; set; }
        public virtual ICollection<TBLSIPARISLER> TBLSIPARISLER { get; set; }
    }
}
