//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDETAYSIPARIS
    {
        public int DETAYID { get; set; }
        public Nullable<int> SIPARISID { get; set; }
        public Nullable<int> URUNID { get; set; }
        public Nullable<int> ADET { get; set; }
        public Nullable<decimal> BIRIMFIYAT { get; set; }
    
        public virtual TBLSIPARISLER TBLSIPARISLER { get; set; }
        public virtual TBLURUNLER TBLURUNLER { get; set; }
    }
}
