//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFIRMA
    {
        public TblFIRMA()
        {
            this.TblGIDER = new HashSet<TblGIDER>();
            this.TblGUNLUKHARCAMA = new HashSet<TblGUNLUKHARCAMA>();
            this.TblSTOKHAREKET = new HashSet<TblSTOKHAREKET>();
            this.TblURUN = new HashSet<TblURUN>();
        }
    
        public int FirmaId { get; set; }
        public string FirmaAdi { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string Adres { get; set; }
        public Nullable<bool> Durumu { get; set; }
    
        public virtual ICollection<TblGIDER> TblGIDER { get; set; }
        public virtual ICollection<TblGUNLUKHARCAMA> TblGUNLUKHARCAMA { get; set; }
        public virtual ICollection<TblSTOKHAREKET> TblSTOKHAREKET { get; set; }
        public virtual ICollection<TblURUN> TblURUN { get; set; }
    }
}
