//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLGIDER
    {
        public TBLGIDER()
        {
            this.TBLCEKSENET = new HashSet<TBLCEKSENET>();
        }
    
        public int GIDERID { get; set; }
        public Nullable<int> TEDARIKCID { get; set; }
        public string GIDERTURU { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string ACIKLAMA { get; set; }
    
        public virtual ICollection<TBLCEKSENET> TBLCEKSENET { get; set; }
        public virtual TBLTEDARIKCILER TBLTEDARIKCILER { get; set; }
    }
}
