//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKATEGORI
    {
        public TblKATEGORI()
        {
            this.TblURUN = new HashSet<TblURUN>();
        }
    
        public int KategoriId { get; set; }
        public string KategoriAdi { get; set; }
    
        public virtual ICollection<TblURUN> TblURUN { get; set; }
    }
}
