//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMASA
    {
        public TblMASA()
        {
            this.TblREZARVASYON = new HashSet<TblREZARVASYON>();
            this.TblSIPARIS = new HashSet<TblSIPARIS>();
            this.TblMUSTERILER = new HashSet<TblMUSTERILER>();
        }
    
        public int MasaId { get; set; }
        public int MasaNo { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public bool Durum { get; set; }
    
        public virtual ICollection<TblREZARVASYON> TblREZARVASYON { get; set; }
        public virtual ICollection<TblSIPARIS> TblSIPARIS { get; set; }
        public virtual ICollection<TblMUSTERILER> TblMUSTERILER { get; set; }
    }
}
