//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMASALAR
    {
        public TBLMASALAR()
        {
            this.TBLADISYONLAR = new HashSet<TBLADISYONLAR>();
            this.TBLREZERVASYONLAR = new HashSet<TBLREZERVASYONLAR>();
            this.TBLSIPARISLER = new HashSet<TBLSIPARISLER>();
        }
    
        public int MASAID { get; set; }
        public string MASANO { get; set; }
        public string KAPASITE { get; set; }
        public string DURUM { get; set; }
    
        public virtual ICollection<TBLADISYONLAR> TBLADISYONLAR { get; set; }
        public virtual ICollection<TBLREZERVASYONLAR> TBLREZERVASYONLAR { get; set; }
        public virtual ICollection<TBLSIPARISLER> TBLSIPARISLER { get; set; }
    }
}
