//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLODEME
    {
        public int ODEMEID { get; set; }
        public Nullable<int> ADISYONID { get; set; }
        public string ODEMETURU { get; set; }
        public Nullable<decimal> ODEMETUTARI { get; set; }
        public Nullable<System.DateTime> ODEMETARIHI { get; set; }
    
        public virtual TBLADISYONLAR TBLADISYONLAR { get; set; }
    }
}
