//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPERSONELLER
    {
        public TblPERSONELLER()
        {
            this.TblBORDROLAR = new HashSet<TblBORDROLAR>();
            this.TblCEKSENET = new HashSet<TblCEKSENET>();
            this.TblGELIR = new HashSet<TblGELIR>();
            this.TblGIDER = new HashSet<TblGIDER>();
            this.TblGUNLUKHARCAMA = new HashSet<TblGUNLUKHARCAMA>();
            this.TblMAAS = new HashSet<TblMAAS>();
            this.TblSIPARIS = new HashSet<TblSIPARIS>();
            this.TblSTOKHAREKET = new HashSet<TblSTOKHAREKET>();
        }
    
        public int PersonelID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string TCKimlikNo { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string Email { get; set; }
        public string Pozisyon { get; set; }
        public System.DateTime Tarih { get; set; }
        public bool Durum { get; set; }
        public string Resim { get; set; }
    
        public virtual ICollection<TblBORDROLAR> TblBORDROLAR { get; set; }
        public virtual ICollection<TblCEKSENET> TblCEKSENET { get; set; }
        public virtual ICollection<TblGELIR> TblGELIR { get; set; }
        public virtual ICollection<TblGIDER> TblGIDER { get; set; }
        public virtual ICollection<TblGUNLUKHARCAMA> TblGUNLUKHARCAMA { get; set; }
        public virtual ICollection<TblMAAS> TblMAAS { get; set; }
        public virtual ICollection<TblSIPARIS> TblSIPARIS { get; set; }
        public virtual ICollection<TblSTOKHAREKET> TblSTOKHAREKET { get; set; }
    }
}
