//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblREZARVASYON
    {
        public int RezarvasyonId { get; set; }
        public int MusteriId { get; set; }
        public int MasaNoId { get; set; }
        public int KisiSayisi { get; set; }
        public System.DateTime Tarih { get; set; }
        public System.TimeSpan Saat { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual TblMASA TblMASA { get; set; }
        public virtual TblMUSTERILER TblMUSTERILER { get; set; }
    }
}
