//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSTOKTAKIP
    {
        public int HAREKETID { get; set; }
        public Nullable<int> MALZEMEID { get; set; }
        public Nullable<int> TEDARIKCID { get; set; }
        public string HAREKETTURU { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> BIRIMFIYAT { get; set; }
        public Nullable<System.DateTime> HAREKETTARIHI { get; set; }
    
        public virtual TBLMALZEMELER TBLMALZEMELER { get; set; }
        public virtual TBLTEDARIKCILER TBLTEDARIKCILER { get; set; }
    }
}
