//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSTOKHAREKET
    {
        public int StokHareketId { get; set; }
        public int UrunId { get; set; }
        public Nullable<int> FirmaId { get; set; }
        public string HareketTipi { get; set; }
        public decimal Miktar { get; set; }
        public decimal BirimFiyat { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> PersonelId { get; set; }
    
        public virtual TblFIRMA TblFIRMA { get; set; }
        public virtual TblPERSONELLER TblPERSONELLER { get; set; }
        public virtual TblURUN TblURUN { get; set; }
    }
}
