//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUNLER
    {
        public TBLURUNLER()
        {
            this.TBLDETAYSIPARIS = new HashSet<TBLDETAYSIPARIS>();
            this.TBLTARIFLER = new HashSet<TBLTARIFLER>();
        }
    
        public int URUNID { get; set; }
        public Nullable<int> KATAGORID { get; set; }
        public string URUNADI { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
    
        public virtual ICollection<TBLDETAYSIPARIS> TBLDETAYSIPARIS { get; set; }
        public virtual ICollection<TBLTARIFLER> TBLTARIFLER { get; set; }
        public virtual TBLURUNKATAGORI TBLURUNKATAGORI { get; set; }
    }
}
