//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjePersonelYonetım
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLVARDIYALAR
    {
        public TBLVARDIYALAR()
        {
            this.TBLCALISANVARDIYA = new HashSet<TBLCALISANVARDIYA>();
        }
    
        public int VARDIYAID { get; set; }
        public string VARDIYADI { get; set; }
        public Nullable<System.TimeSpan> BASLANGICSAATI { get; set; }
        public Nullable<System.TimeSpan> BITISSAATI { get; set; }
        public string AÇIKLAMA { get; set; }
    
        public virtual ICollection<TBLCALISANVARDIYA> TBLCALISANVARDIYA { get; set; }
    }
}
